# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np
from torch import nn
import torch
from torch import optim
import torch.nn.functional as F
import random
from collections import namedtuple, deque
import matplotlib.pyplot as plt

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
env = UnityEnvironment(file_name='Reacher.app')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 1
Size of each action: 4
There are 1 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726671e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [20]:
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1) # all actions between -1 and 1
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

[[-0.79311423  0.18034921  0.08449941 -0.1736024 ]]
[[-0.79311423  0.18034921  0.08449941 -0.1736024 ]]


NameError: name 'a' is not defined

In [8]:
env_info = env.reset(train_mode=False)[brain_name]  
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents) 
actions = [1,1,1,1]
env_info = env.step(actions)[brain_name]


In [9]:
env.step([actions])[brain_name]

In [ ]:
env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [5]:
env_info = env.reset(train_mode=True)[brain_name]

BUFFER_SIZE = int(1e5)  # replay buffer size
BATCH_SIZE = 128        # minibatch size
GAMMA = 0.99          # discount factor
TAU = 0.01#1e-3              # for soft update of target parameters
ACTOR_LR = 5e-4               # learning rate 
CRITICS_LR = 5e-3               # learning rate 
UPDATE_EVERY = 10       # how often to update the network



class Critics_network(nn.Module):
    def __init__(self):
        super().__init__()
        # Defining the layers, 64, 64, 4 units each
        self.fc1 = nn.Linear(33, 128)
        self.fc2 = nn.Linear(128 + 4, 64)
        # Output layer, 4 units - one for each action
        self.fc3 = nn.Linear(64, 4)
    def forward(self, x, action):
        ''' Forward pass through the network, returns the output logits '''
        
        x = self.fc1(x)
        x = F.relu(x)
        x = torch.cat([x, action],1)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        return x

class Actor_network(nn.Module):
    def __init__(self):
        super().__init__()
        # Defining the layers, 64, 64, 4 units each
        self.fc1 = nn.Linear(33, 128)
        self.fc2 = nn.Linear(128, 64)
        # Output layer, 4 units - one for each action
        self.fc3 = nn.Linear(64, 4)
    def forward(self, x):
        ''' Forward pass through the network, returns the output logits '''
        
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
        return F.tanh(x)
        
    
class Agent():
    def __init__(self, seed):
        self.critics_local = Critics_network()
        self.critics_target = Critics_network()
        self.actor_local = Actor_network()
        self.actor_target = Actor_network()
        self.seed = random.seed(seed)
        
        self.actor_optimizer = optim.Adam(self.actor_local.parameters(), lr=ACTOR_LR)
        self.critics_optimizer = optim.Adam(self.critics_local.parameters(), lr=CRITICS_LR)
        self.memory = ReplayBuffer(BUFFER_SIZE, BATCH_SIZE, seed)
        
        self.t_step = 0
        
    def step(self, state, action, reward, next_state, done):
        self.memory.add(state, action, reward, next_state, done)
        
        self.t_step = (self.t_step + 1) % UPDATE_EVERY
        if self.t_step == 0:
            if (len(self.memory)) > BATCH_SIZE:
                samples = self.memory.sample()
                self.learn(samples, GAMMA)
    
    def act(self, state, eps = 0):
        state = torch.from_numpy(state).float()
        with torch.no_grad():
            action_values = self.actor_local(state)
        
        noise = torch.rand(4) * 0.2 - 0.1
        action_values += noise
        return np.clip(action_values, -1, 1)    
            
    def learn(self, samples, gamma):
        "*** YOUR CODE HERE ***"

        states, actions, rewards, next_states, dones = samples
#         print(states.size(), actions.size(), rewards.size(), next_states.size(), dones.size())
        #dimensional fit of rewards and dones
        rewards = rewards.unsqueeze(1)
        dones = dones.unsqueeze(1)

        # Compute Targets
        q_values_next_states = self.critics_local.forward(next_states, self.actor_local(next_states))
#         print("q_values_next_states", q_values_next_states.size())
        targets = rewards + (gamma * (q_values_next_states) *  (1 - dones))
        predictions = self.critics_local.forward(states, actions)
        
#         print(states.size(), actions.size(), rewards.size(), next_states.size(), dones.size())
#         print(q_values_next_states.size(), targets.size(), predictions.size())
        
        # loss & step of critic
        loss = F.mse_loss(predictions, targets)
        self.critics_optimizer.zero_grad()
        loss.backward()
        self.critics_optimizer.step()
        
        # 
        actor_losses = self.critics_local.forward(states, self.actor_local(states))
        actor_loss = - actor_losses.mean()
        self.actor_optimizer.zero_grad()
        actor_loss.backward()
        self.actor_optimizer.step()
        # ------------------- update target network ------------------- #
        self.soft_update(self.critics_local, self.critics_target, TAU)  
        self.soft_update(self.actor_local, self.actor_target, TAU)  

        
 
    def soft_update(self, local_model, target_model, tau):
        """Soft update model parameters.
        θ_target = τ*θ_local + (1 - τ)*θ_target

        Params
        ======
            local_model (PyTorch model): weights will be copied from
            target_model (PyTorch model): weights will be copied to
            tau (float): interpolation parameter 
        """
        for target_param, local_param in zip(target_model.parameters(), local_model.parameters()):
            target_param.data.copy_(tau*local_param.data + (1.0-tau)*target_param.data)


class ReplayBuffer:
    
    def __init__(self, buffer_size, batch_size, seed):
        self.batch_size = batch_size
        self.memory = deque(maxlen = buffer_size)
        self.seed = random.seed(seed)
    
    def add(self, state, action, reward, next_state, done):
        if done:
            done_value = 1
        else:
            done_value = 0
        self.memory.append([state, action, reward, next_state, done_value])
    
    def sample(self):
        samples = (random.sample(self.memory, self.batch_size))
        
        states = []
        actions = []
        rewards = []
        next_states = []
        dones = []
        
        for sample in samples:
            state, action, reward, next_state, done = sample
            
            states.append(torch.tensor(state).float())
            actions.append(torch.tensor(action).float())
            rewards.append(reward)
            next_states.append(next_state)
            dones.append(done)
        
            
        states = torch.cat(states).float().view(len(samples), -1)
        actions = torch.cat(actions).float().view(len(samples), -1)
        rewards = torch.tensor(rewards).float()
        next_states = torch.tensor(next_states).float()
        dones = torch.tensor(dones).float()
        
        return [states,actions,rewards,next_states,dones]
        
    
    def __len__(self):
        return len(self.memory)
        
        

In [6]:
def ddpg(n_episodes=2000, max_t=1000, eps_start=1.0, eps_end=0.0001, eps_decay=0.995):
    env_info = env.reset(train_mode=True)[brain_name]
    agent = Agent(0)
    scores = []                        # list containing scores from each episode
    scores_window = deque(maxlen=100)  # last 100 scores
    eps = eps_start                    # initialize epsilon
    
    for i_episode in range(1, n_episodes+1):
        env.reset()
        state = env_info.vector_observations[0]
        score = 0
        
        for t in range(max_t):
            action = agent.act(state, eps)
            env_info = env.step(action.numpy())[brain_name]        # send the action to the environment
            next_state = env_info.vector_observations[0]   # get the next state
            reward = env_info.rewards[0]                   # get the reward
            done = env_info.local_done[0] 
            agent.step(state, action, reward, next_state, done)
            state = next_state
            score += reward
            if done:
                break
        scores_window.append(score)
        scores.append(score)
        eps = max(eps_end, eps_decay*eps)
        
        if i_episode % 10 == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
        if np.mean(scores_window)>=16.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
            torch.save(agent.qnetwork_local.state_dict(), 'checkpoint.pth')
            break  
    return agent, scores

agent, scores = ddpg()
fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(np.arange(len(scores)), scores)
plt.ylabel('Score')
plt.xlabel('Episode #')
plt.show()

Episode 10	Average Score: 0.75
Episode 20	Average Score: 0.67
Episode 30	Average Score: 0.76
Episode 40	Average Score: 0.83
Episode 50	Average Score: 0.87
Episode 60	Average Score: 0.87
Episode 70	Average Score: 0.80
Episode 80	Average Score: 0.76
Episode 90	Average Score: 0.74
Episode 100	Average Score: 0.72
Episode 110	Average Score: 0.70
Episode 120	Average Score: 0.70
Episode 130	Average Score: 0.67
Episode 140	Average Score: 0.62
Episode 150	Average Score: 0.57
Episode 160	Average Score: 0.53
Episode 170	Average Score: 0.55
Episode 180	Average Score: 0.55
Episode 190	Average Score: 0.54
Episode 200	Average Score: 0.54
Episode 210	Average Score: 0.54
Episode 220	Average Score: 0.53
Episode 230	Average Score: 0.53
Episode 240	Average Score: 0.52
Episode 250	Average Score: 0.51
Episode 260	Average Score: 0.53
Episode 270	Average Score: 0.54
Episode 280	Average Score: 0.53
Episode 290	Average Score: 0.51
Episode 300	Average Score: 0.51
Episode 310	Average Score: 0.49
Episode 320	Avera

KeyboardInterrupt: 

In [156]:
x =  torch.tensor([[1,2,3,4],[5,6,7,8]])
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]])

In [160]:
y = torch.tensor([2,3]).unsqueeze(1)
y

tensor([[ 2],
        [ 3]])

In [26]:
x = torch.rand(100)
x

tensor([ 0.4726,  0.4972,  0.7817,  0.5683,  0.5069,  0.6061,  0.3377,
         0.6289,  0.2883,  0.6252,  0.8945,  0.1141,  0.7922,  0.5070,
         0.7403,  0.2885,  0.6022,  0.9980,  0.0201,  0.9114,  0.6329,
         0.8417,  0.0119,  0.7304,  0.1914,  0.6663,  0.5957,  0.0885,
         0.8278,  0.1150,  0.1106,  0.8401,  0.1309,  0.5620,  0.2234,
         0.6239,  0.6578,  0.5545,  0.1003,  0.9188,  0.6837,  0.9222,
         0.2111,  0.7583,  0.0709,  0.4482,  0.2202,  0.5906,  0.9696,
         0.6697,  0.3073,  0.6539,  0.1845,  0.4986,  0.2524,  0.5659,
         0.8145,  0.1429,  0.2072,  0.3499,  0.1128,  0.7645,  0.3116,
         0.7276,  0.7495,  0.7776,  0.5922,  0.8893,  0.8486,  0.2875,
         0.2591,  0.2948,  0.1777,  0.8752,  0.0434,  0.3813,  0.5381,
         0.2702,  0.0016,  0.4812,  0.6294,  0.6000,  0.5705,  0.2180,
         0.5156,  0.4837,  0.5145,  0.7885,  0.4528,  0.0864,  0.6080,
         0.2496,  0.4371,  0.2815,  0.2573,  0.0903,  0.2012,  0.6269,
      

In [27]:
x = x * 0.2
x

tensor([ 0.0945,  0.0994,  0.1563,  0.1137,  0.1014,  0.1212,  0.0675,
         0.1258,  0.0577,  0.1250,  0.1789,  0.0228,  0.1584,  0.1014,
         0.1481,  0.0577,  0.1204,  0.1996,  0.0040,  0.1823,  0.1266,
         0.1683,  0.0024,  0.1461,  0.0383,  0.1333,  0.1191,  0.0177,
         0.1656,  0.0230,  0.0221,  0.1680,  0.0262,  0.1124,  0.0447,
         0.1248,  0.1316,  0.1109,  0.0201,  0.1838,  0.1367,  0.1844,
         0.0422,  0.1517,  0.0142,  0.0896,  0.0440,  0.1181,  0.1939,
         0.1339,  0.0615,  0.1308,  0.0369,  0.0997,  0.0505,  0.1132,
         0.1629,  0.0286,  0.0414,  0.0700,  0.0226,  0.1529,  0.0623,
         0.1455,  0.1499,  0.1555,  0.1184,  0.1779,  0.1697,  0.0575,
         0.0518,  0.0590,  0.0355,  0.1750,  0.0087,  0.0763,  0.1076,
         0.0540,  0.0003,  0.0962,  0.1259,  0.1200,  0.1141,  0.0436,
         0.1031,  0.0967,  0.1029,  0.1577,  0.0906,  0.0173,  0.1216,
         0.0499,  0.0874,  0.0563,  0.0515,  0.0181,  0.0402,  0.1254,
      

In [28]:
x = x - 0.1
x

tensor(1.00000e-02 *
       [-0.5479, -0.0568,  5.6334,  1.3660,  0.1379,  2.1212, -3.2469,
         2.5782, -4.2341,  2.5050,  7.8899, -7.7188,  5.8431,  0.1405,
         4.8068, -4.2299,  2.0439,  9.9608, -9.5987,  8.2277,  2.6579,
         6.8339, -9.7630,  4.6080, -6.1711,  3.3269,  1.9139, -8.2291,
         6.5568, -7.6991, -7.7873,  6.8025, -7.3814,  1.2392, -5.5316,
         2.4782,  3.1558,  1.0905, -7.9942,  8.3770,  3.6734,  8.4441,
        -5.7779,  5.1654, -8.5829, -1.0363, -5.5954,  1.8122,  9.3917,
         3.3949, -3.8533,  3.0774, -6.3093, -0.0272, -4.9524,  1.3187,
         6.2892, -7.1416, -5.8561, -3.0011, -7.7436,  5.2901, -3.7671,
         4.5525,  4.9904,  5.5513,  1.8439,  7.7860,  6.9716, -4.2499,
        -4.8183, -4.1040, -6.4464,  7.5043, -9.1323, -2.3733,  0.7626,
        -4.5966, -9.9680, -0.3757,  2.5887,  2.0006,  1.4106, -5.6395,
         0.3114, -0.3264,  0.2910,  5.7706, -0.9431, -8.2723,  2.1599,
        -5.0084, -1.2589, -4.3697, -4.8545, -8.1931, -5.